# Generated by Django 3.0.14 on 2021-09-25 03:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='League',
            fields=[
                ('id', models.CharField(max_length=30, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=30)),
                ('sport', models.CharField(max_length=30)),
                ('teams', models.URLField()),
                ('players', models.URLField()),
                ('self', models.URLField()),
            ],
            options={
                'db_table': 'league',
            },
        ),
    ]
