# Generated by Django 3.0.14 on 2021-09-25 16:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('assignment2', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.CharField(max_length=30, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=30)),
                ('city', models.CharField(max_length=30)),
                ('league', models.URLField()),
                ('players', models.URLField()),
                ('self', models.URLField()),
                ('league_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='assignment2.League')),
            ],
            options={
                'db_table': 'team',
            },
        ),
    ]
