# Generated by Django 3.0.14 on 2021-09-25 16:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('assignment2', '0002_team'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='league_id',
            field=models.ForeignKey(db_column='league_id', on_delete=django.db.models.deletion.CASCADE, to='assignment2.League'),
        ),
    ]
