# Generated by Django 3.0.14 on 2021-09-25 20:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('assignment2', '0003_auto_20210925_1655'),
    ]

    operations = [
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.CharField(max_length=30, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=30)),
                ('age', models.PositiveIntegerField()),
                ('position', models.CharField(max_length=30)),
                ('times_trained', models.PositiveIntegerField()),
                ('league', models.URLField()),
                ('team', models.URLField()),
                ('self', models.URLField()),
                ('team_id', models.ForeignKey(db_column='team_id', on_delete=django.db.models.deletion.CASCADE, to='assignment2.Team')),
            ],
            options={
                'db_table': 'player',
            },
        ),
    ]
