# Generated by Django 3.0.14 on 2021-09-26 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assignment2', '0004_player'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='age',
            field=models.PositiveIntegerField(null=True),
        ),
    ]
