# Generated by Django 3.0.14 on 2021-09-26 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assignment2', '0005_auto_20210926_0645'),
    ]

    operations = [
        migrations.AlterField(
            model_name='league',
            name='id',
            field=models.CharField(max_length=200, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='league',
            name='name',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='league',
            name='sport',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='player',
            name='id',
            field=models.CharField(max_length=200, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='player',
            name='name',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='player',
            name='position',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='team',
            name='city',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='team',
            name='id',
            field=models.CharField(max_length=200, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='team',
            name='name',
            field=models.CharField(max_length=200),
        ),
    ]
