# Generated by Django 3.1.13 on 2021-09-26 23:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assignment2', '0006_auto_20210926_0651'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='age',
            field=models.PositiveIntegerField(),
        ),
    ]
